/**
 * utils/safety.js
 * SoulSync Safety & Crisis Prevention Engine
 *
 * Local zero-network detection engine for crisis and life-threatening expressions.
 * Provides a fixed, deterministic response for life-threatening intent so Gemini
 * is NEVER called for high-risk messages.
 */

export const EMERGENCY_PHRASES = [
  'i want to die',
  'i want to kill myself',
  'i am going to kill myself',
  "i'm going to kill myself",
  'i will kill myself',
  'going to end my life',
  'i am going to end my life',
  "i'm going to end my life",
  'end my life',
  'end it all',
  'take my own life',
  'take my life',
  'commit suicide',
  'planning to suicide',
  'i will suicide',
  'i am suicidal',
  "i'm suicidal",
  'i want to hurt myself',
  'i am going to hurt myself',
  "i'm going to hurt myself",
  'i will hurt myself',
  'going to cut myself',
  'want to cut myself',
  'i am going to harm myself',
  "i'm going to harm myself",
  'i will harm myself',
  'going to overdose',
  'want to overdose',
  'going to take pills',
  'no reason to live',
  "don't want to be alive",
  'dont want to be alive',
  'i wish i was dead',
  'i wish i were dead',
  'better off dead',
  'better off without me',
  "don't want to exist",
  'dont want to exist',
  'tired of living',
  'i cannot live anymore',
  "i can't live anymore",
  'i cant live anymore',
  "don't want to live anymore",
  'dont want to live anymore',
  'life is not worth living',
  "life isn't worth living",
  'i will hang myself',
  'going to hang myself',
  // Malayalam equivalents
  'chathukku pokanam',
  'jeevitham mathiayilla',
  'ende jeevitham theerkanam',
  'venam ennu',
  'marichu pokanam',
];

export const CONCERNING_PHRASES = [
  "can't go on", 'cannot go on',
  "can't continue", 'cannot continue',
  "feeling like not continuing", "feel like not continuing",
  "don't feel like continuing", "dont feel like continuing",
  "not continuing",
  "can't take it anymore", 'cannot take it anymore',
  'i give up',
  'no point anymore',
  'nothing to live for',
  'feel empty inside',
  'completely hopeless',
  'lost all hope',
  'nobody cares',
  'nobody would miss me',
  'no one would care',
  'disappear forever',
  'run away forever',
  'feels like the end',
  "don't see a way out",
  'dont see a way out',
  "don't know how much longer",
  "can't keep going",
  'cant keep going',
  'too much pain to handle',
  'feel like giving up',
  'so much pain inside',
  'unbearable pain',
  'everything is pointless',
  'no way forward',
];

export const isLifeThreateningMessage = (text) => {
  if (!text || text.trim().length === 0) return false;
  const t = text.toLowerCase().trim();
  for (const phrase of EMERGENCY_PHRASES) {
    if (t.includes(phrase)) return true;
  }
  return false;
};

export const detectEmergency = (text) => {
  if (!text || text.trim().length === 0) return 'normal';
  if (isLifeThreateningMessage(text)) return 'emergency';
  const t = text.toLowerCase().trim();
  for (const phrase of CONCERNING_PHRASES) {
    if (t.includes(phrase)) return 'concerning';
  }
  return 'normal';
};

/**
 * FIXED CRISIS RESPONSE FOR HIGH_RISK MESSAGES
 * Grounding, supportive, life-affirming response. NEVER generated by AI.
 * Contains ZERO phone numbers or country codes.
 */
export const FIXED_CRISIS_RESPONSE =
  "I'm really sorry you're going through such a painful moment. Please pause and stay with me for the next few minutes. You don't have to make any permanent decision while you're going through this intense moment. What you're feeling right now can change, and you deserve the chance to get through this moment safely.\n\nPlease move away from anything you could use to hurt yourself and, if possible, stay near another person. Take a slow breath and focus only on getting through the next few minutes, not everything at once.\n\nYou don't have to handle this alone. Please contact someone you trust right now and tell them that you need them to stay with you. You can call a trusted person directly from the button below, or ask someone nearby to stay with you.\n\nYou matter, and this moment does not have to decide what happens next. Stay with someone, keep talking, and give yourself time to get through this moment. ❤️";

export const EMERGENCY_AI_PROMPT = `You are SoulSync, a caring companion. The user just expressed serious thoughts of ending their life or harming themselves.

Your ONLY job right now:
- Respond with short warm sentences. No lists, no lectures.
- Acknowledge their pain with deep compassion. Never dismiss it.
- Make them feel heard and NOT alone.
- Do NOT list phone numbers, country helplines, or 988/111 numbers in your reply text.
- Do NOT say "everything will be fine."
- Do NOT claim to be a doctor, therapist, or emergency service.
- End by gently asking if they would like to reach out to someone they trust.
- Respond in the same language the user used.`;

export const CONCERNING_AI_PROMPT = `You are SoulSync, a warm wellness companion. The user is expressing deep emotional pain or hopelessness.

Your role:
- Respond with 2 short warm sentences.
- Acknowledge their pain without minimizing it. Do not offer solutions yet.
- Gently encourage them to keep talking.
- Do NOT list phone numbers, country helplines, or emergency codes in your text.
- Softly ask if they would like to connect with a trusted person or keep sharing with you.
- Do NOT claim to be a therapist or doctor.
- Respond in the same language the user used.`;

export const CRISIS_RESOURCES = [
  { name: 'iCall', number: '9152987821', note: 'Free counselling - Mon-Sat 8am-10pm', emoji: '💬', dialable: '9152987821' },
  { name: 'Tele-MANAS (Govt.)', number: '14416', note: 'Free - 24/7 - Government of India', emoji: '📞', dialable: '14416' },
  { name: 'KIRAN Helpline', number: '1800-599-0019', note: 'Free - 24/7 - Multilingual', emoji: '🤝', dialable: '18005990019' },
  { name: 'Vandrevala Foundation', number: '9999 666 555', note: '24/7 crisis counselling', emoji: '❤️', dialable: '9999666555' },
  { name: 'Emergency Services', number: '112', note: 'Police - Ambulance - Fire', emoji: '🚨', dialable: '112' },
];
